In [1]:
import numpy as np

## Create Numpy Array

In [3]:
np.array([1,2,3,4,5],dtype=np.float64)

array([1., 2., 3., 4., 5.])

In [4]:
np.array([1,2,3,4,5.5],dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [6]:
np.array([1,2,3,4.,5])

array([1., 2., 3., 4., 5.])

In [9]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros(5,dtype=np.int32)

array([0, 0, 0, 0, 0], dtype=int32)

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.random.rand(5)

array([0.50095829, 0.16775024, 0.12125194, 0.38429221, 0.33118348])

In [19]:
np.random.rand(2,3)

array([[0.06960002, 0.92537189, 0.70270831],
       [0.41559126, 0.55391066, 0.19667986]])

In [22]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [23]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.eye(5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
np.arange(2,10,3)

array([2, 5, 8])

In [31]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## shape and reshape numpy array

In [66]:
a = np.array([[12,13,14],[15,16,17]])

In [45]:
print(a)
print("dimention : ",a.ndim)
print("Shape : ",a.shape)
print("Row : ",a.shape[0])
print("Column : ",a.shape[1])
print("size (row*column) : ",a.size)

[[12 13 14]
 [15 16 17]]
dimention :  2
Shape :  (2, 3)
Row :  2
Column :  3
size (row*column) :  6


In [46]:
a

array([[12, 13, 14],
       [15, 16, 17]])

In [47]:
a.reshape((3,2))

array([[12, 13],
       [14, 15],
       [16, 17]])

In [53]:
a.reshape((2,-1))

array([[12, 13, 14],
       [15, 16, 17]])

In [56]:
a.reshape((-1,2))

array([[12, 13],
       [14, 15],
       [16, 17]])

In [67]:
b = a.flatten()
b[0] = 0
print(b)
print(a)

[ 0 13 14 15 16 17]
[[12 13 14]
 [15 16 17]]


In [68]:
b = a.ravel()
b[0] = 0
print(b)
print(a)

[ 0 13 14 15 16 17]
[[ 0 13 14]
 [15 16 17]]


In [70]:
a

array([[ 0, 13, 14],
       [15, 16, 17]])

In [71]:
a.transpose()

array([[ 0, 15],
       [13, 16],
       [14, 17]])

## Expanding and Squeezing a NumPy array

In [72]:
arr = np.array([1,2,3])

In [80]:
print("array : ",np.expand_dims(arr,axis=0))
print("dimention : ",np.expand_dims(arr,axis=0).shape)

array :  [[1 2 3]]
dimention :  (1, 3)


In [81]:
print("array : ",np.expand_dims(arr,axis=1))
print("dimention : ",np.expand_dims(arr,axis=1).shape)

array :  [[1]
 [2]
 [3]]
dimention :  (3, 1)


In [91]:
arr1 = np.array([[1,2,3]])
print(arr1)

[[1 2 3]]


In [92]:
np.squeeze(arr1,axis=0)

array([1, 2, 3])

In [93]:
arr2 = np.array([[1],[2],[3]])
print(arr2)

[[1]
 [2]
 [3]]


In [94]:
np.squeeze(arr2,axis=1)

array([1, 2, 3])

In [95]:
a = np.array([[1,2,3],[4,5,6]])

In [96]:
np.squeeze(a,axis=0)

ValueError: cannot select an axis to squeeze out which has size not equal to one

## Indexing and Slicing of NumPy array

In [97]:
a = np.array([1,2,3,4,5,6])

In [99]:
a[:]

array([1, 2, 3, 4, 5, 6])

In [100]:
a[1:3]

array([2, 3])

In [105]:
a[-3:-1]

array([4, 5])

In [106]:
a[-3:]

array([4, 5, 6])

In [107]:
a[:-3]

array([1, 2, 3])

In [108]:
a[1:5:2]

array([2, 4])

In [109]:
print(a[:6:2])
print(a[1::2])
print(a[1:6:])

[1 3 5]
[2 4 6]
[2 3 4 5 6]


In [110]:
arr = np.array([[1,2,3],[4,5,6]])

In [111]:
arr[0,1]

2

In [113]:
arr[1,2]

6

In [114]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
arr[:,1:]

array([[2, 3],
       [5, 6]])

In [116]:
arr[:,2:]

array([[3],
       [6]])

In [117]:
arr[:,:2]

array([[1, 2],
       [4, 5]])

In [119]:
arr[:,-2:]

array([[2, 3],
       [5, 6]])

In [120]:
arr[:,-2:-1]

array([[2],
       [5]])

In [121]:
arr[1:,1:2]

array([[5]])

In [122]:
a = np.array([[1,2,3],[4,5,6]])
# print first row values
print('First row values :','\n',a[0:1,:])
# with step-size for columns
print('Alternate values from first row:','\n',a[0:1,::2])
# 
print('Second column values :','\n',a[:,1::2])
print('Arbitrary values :','\n',a[0:1,1:3])

First row values : 
 [[1 2 3]]
Alternate values from first row: 
 [[1 3]]
Second column values : 
 [[2]
 [5]]
Arbitrary values : 
 [[2 3]]


In [126]:
arr3 = np.array([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]]])

In [129]:
arr3.ndim

3

In [128]:
arr3

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [130]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [135]:
print(np.flip(a,axis=0))
print(np.flip(a,axis=1))
print(np.flip(a))

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]]
[[10  9  8  7  6]
 [ 5  4  3  2  1]]


## Stacking and Concatenating NumPy arrays

In [138]:
a = np.arange(0,5)
b = np.arange(5,10)

In [141]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [142]:
np.hstack((a,b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
np.dstack((a,b))

array([[[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]]])

In [145]:
np.concatenate((a,b),axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
np.concatenate((np.expand_dims(a,axis=0),np.expand_dims(b,axis=0)),axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [160]:
np.concatenate((np.expand_dims(a,axis=0),np.expand_dims(b,axis=0)),axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [164]:
a = np.array([[1,2],
             [3,4]])
np.append(a,[[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [172]:
a = np.array([1,2,3,4,5])
np.append(a,[6,7,9,3,4],axis=0)

array([1, 2, 3, 4, 5, 6, 7, 9, 3, 4])

## Broadcasting in NumPy arrays – A class apart!

In [173]:
a = np.arange(10,20,2)

In [178]:
b = np.array([[2],[2]])

In [180]:
a+b

array([[12, 14, 16, 18, 20],
       [12, 14, 16, 18, 20]])

In [191]:
a = np.ones((3,3))

In [194]:
b = np.array([2])

In [195]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

## Maths with NumPy arrays

In [197]:
a = np.array([1,2,3,4,5])

In [198]:
print('Subtract :',a-5)
print('Multiply :',a*5)
print('Divide :',a/5)
print('Power :',a**2)
print('Remainder :',a%5)

Subtract : [-4 -3 -2 -1  0]
Multiply : [ 5 10 15 20 25]
Divide : [0.2 0.4 0.6 0.8 1. ]
Power : [ 1  4  9 16 25]
Remainder : [1 2 3 4 0]


In [199]:
a = np.arange(5,15,2)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


In [200]:
a = np.array([[1,6],
[4,3]])
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))

Min : [1 3]
Max : [6 4]


In [201]:
a = np.array([[1,6,5],
[4,3,7]])
# minimum along a column
print('Min :',np.argmin(a,axis=0))
# maximum along a row
print('Max :',np.argmax(a,axis=1))

Min : [0 1 0]
Max : [1 2]


## Sorting in NumPy arrays

In [202]:
a = np.array([1,4,2,5,3,6,8,7,9])
np.sort(a, kind='quicksort')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
a = np.array([[5,6,7,4],
              [9,2,3,7]])# sort along the column
print('Sort along column :','\n',np.sort(a, kind='mergresort',axis=1))
# sort along the row
print('Sort along row :','\n',np.sort(a, kind='mergresort',axis=0))

Sort along column : 
 [[4 5 6 7]
 [2 3 7 9]]
Sort along row : 
 [[5 2 3 4]
 [9 6 7 7]]


## NumPy Ufuncs – The secret of its success!